### ISSUE TITLE
尝试了多次后依然超时报错

### ISSUE THREAD

**Issue by highsea** [alsotang/externalip#2]
#### 路由部分：

    var externalip = require('externalip');
    externalip(function (err, ip) {
        if (err) console.log(err)
        console.log(ip);
    });

#### 输出：

    data: {
        code: "ETIMEDOUT",
        errno: "ETIMEDOUT",
        syscall: "connect"
    }

**Comment by alsotang** [comment]
use https://github.com/sindresorhus/public-ip

this package is deprecated


2015-06-15 16:34 GMT+08:00 高海 <notifications@github.com>:

**Comment by highsea** [comment]
0.0 ……
