### ISSUE TITLE
Question: State of OpenDNS in China

### ISSUE THREAD

**Issue by justinpage** [alsotang/externalip#3]
### Question

Is OpenDNS still an issue in China?
### Discussion

I came across this plugin, out of many that attempt public IP address lookup, and was curious about your readme statement. After a quick search, it looks like OpenDNS put out a statement:

https://support.opendns.com/entries/95836508-OpenDNS-and-China-

Is OpenDNS support internationally pretty strong or is it still something we are exploring?

**Comment by alsotang** [comment]
One important method that China gov used to block Chinese network is dns pollution.

So 8.8.8.8 and opendns is somehow unstable in China. 

I dont know whether opendns is available now, and wont test it. I simply dont trust our gov.

**Comment by alsotang** [comment]
![image](https://cloud.githubusercontent.com/assets/1147375/14761960/225d9256-09a1-11e6-8e61-7bd6ffdcd0a7.png)


I just test `public-ip`, and opendns is not work

**Comment by alsotang** [comment]
https://github.com/sindresorhus/public-ip

**Comment by KLVTZ** [comment]
@alsotang thanks for checking! It's unfortunate that this sort of blocking is in place.

**Comment by alsotang** [comment]
Accustomed, for many years........

2016-04-24 0:38 GMT+08:00 Justin Page <notifications@github.com>:
