### ISSUE TITLE
这个是基于什么原理写的了

### ISSUE THREAD

**Issue by wuyanwen** [alsotang/externalip#4]
我发现里面有这个url,https://diagnostic.opendns.com/myip,本地访问不了，但这个包可以用，求解释原因，放到线上，有影响吗，和这个url能不能访问有关系吗

**Comment by alsotang** [comment]
这个包应该也不能用吧？

https://diagnostic.opendns.com/myip 这个网址可能在国内被封了。

这个包不要放到线上用，我已经不维护了。

**Comment by alsotang** [comment]
我简单修了一下，现在使用 ip.cn 的服务，现在可用了。

**Comment by wuyanwen** [comment]
OK了，多谢
