### ISSUE TITLE
Vulnerabilities due to dependencies

### ISSUE THREAD

**Issue by Berkmann18** [alsotang/externalip#5]
After running a live NSP scan.
I've noticed that this package is vulnerable to:

Large gzip DoS (due to superagent@0.18.2 which needs to be updated to v3.7+)
https://nodesecurity.io/advisories/479
DoS extended Event loop blocking and DoS memory exhaustion (due to qs@0.6.6 not being at least at v1.0)
https://nodesecurity.io/advisories/28
https://nodesecurity.io/advisories/29
RE DoS (due to mime@1.2.11 that needs to be updated to v2.0.3 and debug@1.0.5 that needs to be updated to v3.1.0)
https://nodesecurity.io/advisories/535
https://nodesecurity.io/advisories/534

**Comment by Sv443** [comment]
Yup, getting this too.

Quick fix:
- go to the `node_modules` folder and delete `superagent`
- go to the externalip folder and change the superagent dependency line to this: `"superagent": ">=3.7.0"`
- run `npm i --save`

**Comment by alsotang** [comment]
I dont even know if this project can run as expected. Just use https://github.com/sindresorhus/public-ip

**Comment by alsotang** [comment]
updated `superagent` to `4.1.0`

**Comment by Sv443** [comment]
> 
> 
> I dont even know if this project can run as expected. Just use https://github.com/sindresorhus/public-ip

I've tried many different modules and I don't know why but yours is the only one that worked flawlessly so far (even though it's a bit slow)
